### ISSUE TITLE
What does this project do?

### ISSUE THREAD

**Issue by lancecarlson** [KissKissBankBank/streaker#14]
Sorry if I'm missing something, but why does this project exist outside of streak-ruby?

**Comment by sunny** [comment]
Hi Lance, good question, glad you asked! `streak-ruby` is a rather low-level API with a 1-1 relationship to the REST calls and to its internal codes.

Therefore, to create a box, you need to :

```rb
box = Streak::Box.create('4aa9c4166d035e20b067fd3aea25b790', name: 'Box name here')
Streak::Box.update(box.key, stageKey: 3009)
Streak::FieldValue.update(box.key, 1008, value: 'foo@example.com')
Streak::FieldValue.update(box.key, 1009, value: 'Some example value')
Streak::FieldValue.update(box.key, 1010, value: 'Another value')
Streak::FieldValue.update(box.key, 1012, value: '1/1/2000')
# and so forth for each value…
```

Whereas, with Streaker (which actually uses `streak-ruby` internally), you only need to:

```rb
Streaker::Box.create(
  name: 'Box name here',
  email: 'foo@example.com',
  some_field: 'Some example value',
  another_field: 'Another value',
  birthdate: '1/1/2000',
  # and so forth for each value…
)
```

The syntax is simpler, does not treat the box name and stage as different calls, provides better error handling and maps these numbers (that represent fields, stages, etc.) in a neat configuration.
